// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SirinEngineering.Models.db;

#nullable disable

namespace SirinEngineering.Migrations
{
    [DbContext(typeof(projectContext))]
    [Migration("20260321154748_InitialDatabaseWithPrefix")]
    partial class InitialDatabaseWithPrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SirinEngineering.Models.db.CategoryModel", b =>
                {
                    b.Property<int>("C_CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("C_CategoryID"));

                    b.Property<string>("C_CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("C_CategoryID");

                    b.ToTable("TBL_Category");
                });

            modelBuilder.Entity("SirinEngineering.Models.db.OrderModel", b =>
                {
                    b.Property<int>("O_OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("O_OrderID"));

                    b.Property<string>("O_CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("O_DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("O_GiftItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("O_OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("O_PaymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("O_Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("O_ProductID")
                        .HasColumnType("int");

                    b.Property<string>("O_ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("O_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("O_Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("O_SubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("O_TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("O_UserID")
                        .HasColumnType("int");

                    b.HasKey("O_OrderID");

                    b.ToTable("TBL_Order");
                });

            modelBuilder.Entity("SirinEngineering.Models.db.PaymentModel", b =>
                {
                    b.Property<int>("PY_PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PY_PaymentID"));

                    b.Property<decimal>("PY_Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PY_OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PY_PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PY_PaymentSlip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PY_Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PY_PaymentID");

                    b.ToTable("TBL_Payment");
                });

            modelBuilder.Entity("SirinEngineering.Models.db.ProductModel", b =>
                {
                    b.Property<int>("PD_ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PD_ProductID"));

                    b.Property<string>("PD_Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PD_CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("PD_Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("PD_IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PD_MinStock")
                        .HasColumnType("int");

                    b.Property<decimal>("PD_Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PD_ProductImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PD_ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PD_StockQty")
                        .HasColumnType("int");

                    b.HasKey("PD_ProductID");

                    b.ToTable("TBL_Product");
                });

            modelBuilder.Entity("SirinEngineering.Models.db.PromotionModel", b =>
                {
                    b.Property<int>("PM_PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PM_PromotionID"));

                    b.Property<string>("PM_Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PM_DiscountValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PM_EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PM_FreeQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("PM_IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("PM_MaxGiftValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("PM_MinQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("PM_MinSpend")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PM_PromoType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PM_PromotionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PM_StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PM_TargetCategoryID")
                        .HasColumnType("int");

                    b.HasKey("PM_PromotionID");

                    b.ToTable("TBL_Promotion");
                });

            modelBuilder.Entity("SirinEngineering.Models.db.RoleModel", b =>
                {
                    b.Property<int>("R_RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("R_RoleID"));

                    b.Property<string>("R_RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("R_RoleID");

                    b.ToTable("TBL_Role");
                });

            modelBuilder.Entity("SirinEngineering.Models.db.UserModel", b =>
                {
                    b.Property<int>("U_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("U_UserID"));

                    b.Property<string>("U_FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("U_IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("U_Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("U_Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("U_RoleID")
                        .HasColumnType("int");

                    b.Property<string>("U_Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("U_UserID");

                    b.ToTable("TBL_User");
                });
#pragma warning restore 612, 618
        }
    }
}
